### ISSUE TITLE
進化為 AHK-Reminder 如何？

### ISSUE THREAD

**Issue by yoxahu** [eight04/AHK-Timer#1]
如果「提醒視窗」可以像早年的 MSN Messenger 一樣，一層一層往上疊疊樂，蓋大樓，看起來一定相當爽！
（也一目了然，一堆事在忙時，可以等有空閒，再來慢慢確認）（系統列圖示選項提供一鍵「確認所有提醒」）

然後所有「事件項目」不要一倒數完/確認完就刪除，設計為可重複使用（這樣下次要泡麵就不用再輸入一次「泡麵」、「2」），並且由「計時器管理」頁面統一管理，並賦予各「事件項目」以下功能：

。允許各「事件項目」於「計時器管理」內進行修改各項屬性（修改 倒數時間、提醒標題、刪除項目 等）
。提供設置「active on/off」開關，若設置為「active on」，則隨著程式啟動一律自動開始倒數計時（需取消 active 狀態才能進行前述修改屬性與刪除的動作）
。使用者收到「提醒視窗」並按下「確認」後，「active」狀態即為「off」，而倒數值恢復為原設置，不歸零
。若新增事件「倒數計時」值為零，則視「active on/off」狀態決定於程式啟動時，是否立即跳出「提醒視窗」
。提供設置「倒數循環次數」和「每次循環長度」（後者現行版本已具備）
。提供設置「事件項目」欄位(列)底色，至少有便利貼常見的 淡藍、粉紅、淡黃、淡綠 等，作為區分類別之用
。依前述「事件項目」欄位(列)底色，「提醒視窗」也顯示為同樣的底色
。於「計時器管理」頁面提供「all active off」對所有事件同時停止，與「delete all/all expired」的按鈕（active on 的項目無法被 delete）
。於「計時器管理」頁面提供「重新整理」按鈕，按下的同時執行「各項目依到期日排序」

裝備以上功能即可將 AHK-Timer 升級為 AHK-Reminder

。如果可行，提供各「事件項目」個別指定獨立的音效提示檔
。如果可行，追加「整點報時」功能
。如果可行，追加「定時鬧鐘」功能（從單日鬧鐘 → 能夠設定每週一三五啟動 → 設定指定日期）
。如果可行，24 小時內逾期的項目變為 紅色粗體字（可由使用者定義接近逾期的時間範圍）
。如果可行，啟動程式時，若存在 24 小時內逾期的項目，則立即跳出「提醒視窗」，時間到再通知一次
。如果可行，追加「貪睡功能」（收到通知後，延遲 N 分鐘之後再通知一次）
。如果可行，追加「觸發外部目標」功能（批次檔、執行檔、媒體檔 等）
。如果可行，追加「關鍵字過濾器」迅速檢視想要尋找、編輯的項目

裝備以上功能則進化為 AHK-Reminder Professional，可以考慮轉為收費軟體了 XD

（然後獲得「AHK 達人」的稱號！！！）

**Comment by eight04** [comment]
在請求新功能時，請將各項功能分不同 issue 討論。

我懷疑這些功能是否必要。當初寫這個程式的目的有三個︰

1. 小
2. 只需要鍵盤即可使用
3. 時間到時提醒使用者

如果是要更複雜的鬧鐘功能，我想有很多更專業的軟體比較符合你的需求。

**Comment by yoxahu** [comment]
不好意思，一接觸到這隻程式，腦袋就忍不住冒出這些，不吐不快！（也只會嘴砲，不會寫程式 XD）

以您的預設目標而言，至少可以做到：

「下次要執行與前次一樣的提醒任務時，不需要再重複輸入一次。」（只須勾選已存在/輸入過的項目）

如果想減少滑鼠操作，那就設一個熱鍵來呼叫「管理面版」，比方說 WinKey+Shift+T

然後 Shift+F1~F12 分別依序對應「管理面版」留存的至多十二個項目的 checkbox，被勾選的項目即開始倒數

（或者每頁至多顯示十二項，以 Page Up/Down 鍵翻頁...）

**Comment by eight04** [comment]
> 下次要執行與前次一樣的提醒任務時，不需要再重複輸入一次。

這個構想是好的。如果要做的話可以讓使用者提供一些預設的計時器，在按下 Win-T 後再用快速鍵填入。
